runtime: nodejs
env: flex

network:
  session_affinity: true

env_variables:
  EXAUTH: https://ex-auth-dot-stoked-reality-284921.ew.r.appspot.com
  EXGATEWAYCACHEIP: 10.56.0.4
  EXGATEWAYCACHEPORT: 6379