runtime: nodejs
env: flex

network:
  name: default
  session_affinity: true

manual_scaling:
  instances: 1

env_variables:
  EXAUTH: $EXAUTH
  EXGATEWAYCACHEIP: $EXGATEWAYCACHEIP
  EXGATEWAYCACHEPORT: $EXGATEWAYCACHEPORT
  SOURCE: app-engine
