runtime: nodejs
env: flex

network:
  name: default
  session_affinity: true

env_variables:
  EXAUTH: $EXAUTH
  EXGATEWAYCACHEIP: $EXGATEWAYCACHEIP
  EXGATEWAYCACHEPORT: $EXGATEWAYCACHEPORT
  SOURCE: app-engine
