runtime: nodejs
env: flex

network:
  name: default

manual_scaling:
  instances: 1

session_affinity: true

resources:
  memory_gb: 4

env_variables:
  EXAUTH: $EXAUTH
  EXGATEWAYCACHEIP: $EXGATEWAYCACHEIP
  EXGATEWAYCACHEPORT: $EXGATEWAYCACHEPORT
  SOURCE: app-engine
